# Copyright (C) 2026 Oddur Sigurdsson
# SPDX-License-Identifier: GPL-3.0-or-later

[workspace]
resolver = "3"
members = [
    "crates/crabbucket",
    "crates/crabbucket-cli",
    "crates/crabbucket-routes",
    "crates/crabbucket-theme-plain",
    "crates/crabbucket-tokens",
    "crates/crabbucket-ui",
    "examples/site-crate",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Oddur Sigurdsson <oddurs@gmail.com>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/oddurs/crabbucket"
readme = "README"

[workspace.dependencies]
crabbucket = { path = "crates/crabbucket", version = "0.1.0" }
crabbucket-routes = { path = "crates/crabbucket-routes", version = "0.1.0" }
crabbucket-theme-plain = { path = "crates/crabbucket-theme-plain", version = "0.1.0" }
crabbucket-tokens = { path = "crates/crabbucket-tokens", version = "0.1.0" }
crabbucket-ui = { path = "crates/crabbucket-ui", version = "0.1.0" }

[profile.release]
lto = true
codegen-units = 1
strip = true
